presubmits:
  - name: pull-helm-charts-render
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/helm-charts"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.25.0-1
          command:
            - hack/ci/render-helm-charts.sh
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
